### ISSUE TITLE
404 for docs.ropensci.org/rcademy

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/Rcademy#8]
The docs.ropensci.org link will only work for packages in the ropensci GitHub org, not ropenscilabs.

Can you please remove the link?

**Comment by robjhyndman** [comment]
Where is the link? I can't find any reference to docs.opensci.org in the rcademy package.

**Comment by stefaniebutland** [comment]
![Screen Shot 2020-02-04 at 1 22 09 PM](https://user-images.githubusercontent.com/11927811/73788150-5c9df400-4751-11ea-9e77-02989adccb0c.png)

**Comment by robjhyndman** [comment]
Ah, ok. But not being an ropenscilabs admin, I don't think I remove it. At least, the usual edit link is missing for me.

**Comment by stefaniebutland** [comment]
I'll check on this. Thought someone from the team had added it.

**Comment by stefaniebutland** [comment]
Link removed by rOpenSci team.

I mis-spoke about this, so clarifying:
> The docs.ropensci.org link will only work for packages in the ropensci GitHub org, not ropenscilabs.

The docs are built for *some* ropenscilabs packages, but not for early experimental stages.
